theme: jekyll-theme-cayman

title: "WiFiTrace"
#email: "{firstname}trivedi@umass.edu"
description: WiFi based Contact Tracing
baseurl: "" #"/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: amee_tweets
github_username:  ameetrivedi
